### ISSUE TITLE
missprint on #6

### ISSUE THREAD

**Issue by bm0329** [mootoh/iOS_SDK_Hacks#1]
本書#6 P12,P13の小見出し
"MyCellContentViewクラスの実装"
と
"MyCellContentViewクラスの実装"
が逆かと思います。

**Comment by watr** [comment]
"MyCellContentViewクラスの実装"と
"MyTableViewCellクラスの実装"
かと思います。

また、p.12 本文1行目の
"セルMyTableViewクラスと、..."
は
"セルMyTableViewCellクラスと、..."が正しいようにも思えます。
