### ISSUE TITLE
P133 SKProductRequestのalloc initの所

### ISSUE THREAD

**Issue by noborunrun** [mootoh/iOS_SDK_Hacks#10]
nameをNSStringで受けて、
SKProductsRequest *requeest;
request = [[SKProductsRequest alloc] initWithProductIdentifiers:name];
とありますが、
- (id)initWithProductIdentifiers:(NSSet *)productIdentifiers
  なので、
  request = [[SKProductsRequest alloc] initWithProductIdentifiers:[NSSet setWithObject:name]];
  だと思います。

ご確認のほど、よろしくお願いいたします。

**Comment by sonsongithub** [comment]
3刷修正します．
