### ISSUE TITLE
xibファイルがxcodeプロジェクトにバンドルされていない

### ISSUE THREAD

**Issue by hirohitokato** [mootoh/iOS_SDK_Hacks#15]
## 概要

CameraPixelプロジェクトで、プロジェクトにMainWindow.xibファイルとRootViewController.xibファイルがバンドルされていませんでした（ファイルそのものは存在していました）
## 再現手順
1. サンプルをダウンロード
2. Xcode3.2.5でCameraPixelプロジェクトを開く
3. Resourcesグループを開く
4. 内容を確認する
### 期待する結果
- MainWindow.xibファイルとRootViewController.xibファイルが表示される
- （プロジェクトが問題なく実行出来る）
### 実際の結果
- MainWindow.xibファイルとRootViewController.xibファイルが無い
- プロジェクトを実行するとMainWindow.xibが無いことで強制終了する

手元ではxibファイル2つをプロジェクトにドラッグ＆ドロップで追加して、無事に実行されることを確認しました。

**Comment by sonsongithub** [comment]
修正しました．
