### ISSUE TITLE
#33 p.100 calc_neon

### ISSUE THREAD

**Issue by watr** [mootoh/iOS_SDK_Hacks#6]
関数 calc_neon(int n) 内、for文の内部で
vaddq_u32(_src4, *src4);
とありますが、「配列の内容を2乗してコピーする」ならば
vmulq_s32(_src4, *src4);
の誤りでしょうか。

また、calc_neon の戻り値が double になっていますが、何も返していないので void かと思います。

**Comment by mootoh** [comment]
fixed in ch0406.
