### ISSUE TITLE
#39 p.151 vDSP_dotpr 引数の解説

### ISSUE THREAD

**Issue by watr** [mootoh/iOS_SDK_Hacks#9]
ページ中段 vDSP_dotpr の下の段落先頭、「第3引数は、」は誤りで「第5引数は、」が正しいかと思います。
また、段落2行目の「dotProductのポインタを指定し。」の最後の句点はミスプリントで読点「、」が正しいかと思います。

**Comment by sonsongithub** [comment]
3刷で修正
